# Generated by Django 4.0.2 on 2022-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreastCancerPaper',
            fields=[
                ('country', models.TextField(blank=True, null=True)),
                ('pubmed_id', models.IntegerField(blank=True, db_column='Pubmed ID', primary_key=True, serialize=False)),
                ('authors', models.TextField(blank=True, null=True)),
                ('comparative_study', models.TextField(blank=True, db_column='Comparative study', null=True)),
                ('participants_cancer_control_field', models.TextField(blank=True, db_column='participants (Cancer/ Control)', null=True)),
                ('material_source_field', models.TextField(blank=True, db_column='material (source)', null=True)),
                ('function', models.TextField(blank=True, null=True)),
                ('participants_cancer_type_field', models.TextField(blank=True, db_column='participants\n(cancer type)', null=True)),
                ('stage', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('gender_m_f_field', models.TextField(blank=True, db_column='gender (M / F)', null=True)),
                ('age_mean_range_m_f_field', models.TextField(blank=True, db_column='age mean (range) (M / F)', null=True)),
                ('smoking_status', models.TextField(blank=True, db_column='smoking status', null=True)),
                ('participants_control_field', models.TextField(blank=True, db_column='participants\n(control)', null=True)),
                ('number_1', models.IntegerField(blank=True, db_column='number.1', null=True)),
                ('gender_m_f_1', models.TextField(blank=True, db_column='gender (M / F).1', null=True)),
                ('age_mean_range_m_f_field_0', models.TextField(blank=True, db_column='age mean (range) (M / F).', null=True)),
                ('smoking_status_1', models.TextField(blank=True, db_column='smoking status.1', null=True)),
                ('chromatography', models.TextField(blank=True, null=True)),
                ('ion_source', models.TextField(blank=True, db_column='ion source', null=True)),
                ('positive_negative_mode', models.TextField(blank=True, db_column='positive/ negative mode', null=True)),
                ('mass_analyzer', models.TextField(blank=True, db_column='mass analyzer', null=True)),
                ('identification_level', models.TextField(blank=True, db_column='Identification level', null=True)),
                ('data_processing_software', models.TextField(blank=True, db_column='data processing software', null=True)),
                ('database_search', models.TextField(blank=True, db_column='database search', null=True)),
                ('statistical_difference_method', models.TextField(blank=True, db_column='statistical difference method', null=True)),
                ('classification_method', models.TextField(blank=True, db_column='classification method', null=True)),
                ('survival_analysis_method', models.TextField(blank=True, db_column='survival analysis method', null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'breast_cancer_paper',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='metaboliteinf',
            table='Metabolite_inf',
        ),
    ]
