# Generated by Django 4.0.2 on 2022-06-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_breastcancermet'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='breastcancermet',
            table='breast_cancer_met',
        ),
    ]
