# Generated by Django 4.0.2 on 2022-08-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0010_kidneycancerther'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorectalCancerTher',
            fields=[
                ('metabolite_paper_field', models.TextField(blank=True, db_column='metabolite (paper)', null=True)),
                ('specimen', models.TextField(blank=True, db_column='Specimen', null=True)),
                ('function', models.TextField(blank=True, null=True)),
                ('drug_therapy', models.TextField(blank=True, db_column='Drug therapy', null=True)),
                ('number_of_injections', models.TextField(blank=True, db_column='Number of injections', null=True)),
                ('period_between_injection_and_response_evaluation', models.TextField(blank=True, db_column='Period between injection and response evaluation', null=True)),
                ('participants_response_non_responsel_field', models.TextField(blank=True, db_column='participants (Response/ Non-responsel)', null=True)),
                ('statistical_difference_method', models.TextField(blank=True, db_column='statistical difference method', null=True)),
                ('mean_concentration_case_μmol_l_field', models.TextField(blank=True, db_column='mean concentration (case) (µmol/L)', null=True)),
                ('mean_concentration_control_μmol_l_field', models.TextField(blank=True, db_column='mean  concentration (control) (µmol/L)', null=True)),
                ('fold_change_n_case_control_field', models.TextField(blank=True, db_column='fold change n(case/ control)', null=True)),
                ('change_direction', models.TextField(blank=True, db_column='Change direction', null=True)),
                ('raw_p_value', models.TextField(blank=True, db_column='RAW p-value', null=True)),
                ('fdr', models.TextField(blank=True, null=True)),
                ('vip', models.TextField(blank=True, null=True)),
                ('classification_method', models.TextField(blank=True, db_column='Classification method', null=True)),
                ('cutoff_value', models.TextField(blank=True, db_column='Cutoff value', null=True)),
                ('auroc_95_ci_field', models.TextField(blank=True, db_column='AUROC (95%%CI)', null=True)),
                ('sensitivity_field', models.TextField(blank=True, db_column='Sensitivity (%%)', null=True)),
                ('specificity_field', models.TextField(blank=True, db_column='Specificity (%%)', null=True)),
                ('accuracy_field', models.TextField(blank=True, db_column='Accuracy (%%)', null=True)),
                ('time_cut_offs_field', models.TextField(blank=True, db_column='time cut-offs (<=/>)', null=True)),
                ('hr_95_ci_field', models.TextField(blank=True, db_column='HR (95%%CI)', null=True)),
                ('p_value', models.TextField(blank=True, db_column='p-value', null=True)),
                ('fdr_1', models.TextField(blank=True, db_column='FDR.1', null=True)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('author_emphasized_biomarkers', models.TextField(blank=True, db_column='author-emphasized biomarkers', null=True)),
                ('other_information', models.TextField(blank=True, db_column='other information', null=True)),
                ('pubmed_id', models.TextField(blank=True, db_column='Pubmed ID', null=True)),
                ('authors', models.TextField(blank=True, db_column='Authors', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'colorectal_cancer_ther',
                'managed': False,
            },
        ),
    ]
