# Generated by Django 4.0.2 on 2022-08-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0012_arthritiscancerther_depressioncancerther'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvdCancerOurs',
            fields=[
                ('hmdb', models.TextField(blank=True, null=True)),
                ('metabolite_paper_field', models.TextField(blank=True, db_column='metabolite (paper)', primary_key=True, serialize=False)),
                ('regulation', models.TextField(blank=True, db_column='Regulation', null=True)),
                ('specimen', models.TextField(blank=True, db_column='Specimen', null=True)),
                ('function', models.TextField(blank=True, null=True)),
                ('statistical_software', models.TextField(blank=True, db_column='statistical software', null=True)),
                ('statistical_difference_method', models.TextField(blank=True, db_column='statistical difference method', null=True)),
                ('mean_concentration_case_field', models.TextField(blank=True, db_column='mean concentration (case)', null=True)),
                ('mean_concentration_control_field', models.TextField(blank=True, db_column='mean  concentration (control)', null=True)),
                ('fold_change_n_case_control_field', models.TextField(blank=True, db_column='fold change n(case/ control)', null=True)),
                ('raw_p_value', models.TextField(blank=True, db_column='RAW p-value', null=True)),
                ('fdr', models.TextField(blank=True, null=True)),
                ('vip', models.TextField(blank=True, null=True)),
                ('classification_method', models.TextField(blank=True, db_column='Classification method', null=True)),
                ('cutoff_value', models.TextField(blank=True, db_column='Cutoff value', null=True)),
                ('auroc_95_ci_field', models.TextField(blank=True, db_column='AUROC (95%%CI)', null=True)),
                ('sensitivity_field', models.TextField(blank=True, db_column='Sensitivity (%%)', null=True)),
                ('specificity_field', models.TextField(blank=True, db_column='Specificity (%%)', null=True)),
                ('accuracy_field', models.TextField(blank=True, db_column='Accuracy (%%)', null=True)),
                ('survival_analysis_method', models.TextField(blank=True, db_column='Survival analysis method', null=True)),
                ('time_cut_offs_field', models.TextField(blank=True, db_column='time cut-offs (<=/>)', null=True)),
                ('hr_95_ci_field', models.TextField(blank=True, db_column='HR (95%%CI)', null=True)),
                ('p_value', models.TextField(blank=True, db_column='p-value', null=True)),
                ('fdr_1', models.TextField(blank=True, db_column='FDR.1', null=True)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('author_emphasized_biomarkers', models.TextField(blank=True, db_column='author-emphasized biomarkers', null=True)),
                ('other_information', models.TextField(blank=True, db_column='other information', null=True)),
                ('pubmed_id', models.TextField(blank=True, db_column='Pubmed ID', null=True)),
                ('authors', models.TextField(blank=True, db_column='Authors', null=True)),
            ],
            options={
                'db_table': 'CVD_cancer_ours ',
                'managed': False,
            },
        ),
    ]
