# Generated by Django 4.0.2 on 2022-09-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0016_prostatecancerther'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProstateCancerTherPubl',
            fields=[
                ('country', models.TextField(blank=True, null=True)),
                ('pubmed_id', models.IntegerField(blank=True, db_column='Pubmed ID', primary_key=True, serialize=False)),
                ('authors', models.TextField(blank=True, null=True)),
                ('comparative_study', models.TextField(blank=True, db_column='Comparative study', null=True)),
                ('disease', models.TextField(blank=True, db_column='Disease', null=True)),
                ('drug_therapy', models.TextField(blank=True, db_column='Drug therapy', null=True)),
                ('number_of_injections', models.TextField(blank=True, db_column='Number of injections', null=True)),
                ('period_between_injection_and_response_evaluation', models.TextField(blank=True, db_column='Period between injection and response evaluation', null=True)),
                ('assessment_criteria', models.TextField(blank=True, db_column='Assessment criteria', null=True)),
                ('material_source_field', models.TextField(blank=True, db_column='material (source)', null=True)),
                ('function', models.TextField(blank=True, null=True)),
                ('number_of_responded_participants', models.TextField(blank=True, db_column='number of responded participants', null=True)),
                ('gender_m_f_of_responded_participants', models.TextField(blank=True, db_column='gender (M / F) of responded participants', null=True)),
                ('age_mean_range_m_f_of_responded_participants', models.TextField(blank=True, db_column='age mean (range) (M / F) of responded participants', null=True)),
                ('number_of_non_responded_participants', models.TextField(blank=True, db_column='number of non-responded participants', null=True)),
                ('gender_m_f_of_non_responded_participants', models.TextField(blank=True, db_column='gender (M / F) of non-responded participants', null=True)),
                ('age_mean_range_m_f_of_non_responded_participants', models.TextField(blank=True, db_column='age mean (range) (M / F of non-responded participants', null=True)),
                ('chromatography', models.TextField(blank=True, null=True)),
                ('ion_source', models.TextField(blank=True, db_column='ion source', null=True)),
                ('positive_negative_mode', models.TextField(blank=True, db_column='positive/ negative mode', null=True)),
                ('mass_analyzer', models.TextField(blank=True, db_column='mass analyzer', null=True)),
                ('identification_level', models.TextField(blank=True, db_column='Identification level', null=True)),
                ('data_processing_software', models.TextField(blank=True, db_column='data processing software', null=True)),
                ('database_search', models.TextField(blank=True, db_column='database search', null=True)),
                ('statistical_difference_method', models.TextField(blank=True, db_column='statistical difference method', null=True)),
                ('classification_method', models.TextField(blank=True, db_column='classification method', null=True)),
                ('survival_analysis_method', models.TextField(blank=True, db_column='survival analysis method', null=True)),
                ('год', models.TextField(blank=True, db_column='Год', null=True)),
            ],
            options={
                'db_table': 'prostate_cancer_ther_publ',
                'managed': False,
            },
        ),
    ]
